export const componentGroups = [
  'Buttons & Actions',
  'Form Inputs',
  'Feedback & Status',
  'Navigation',
  'Data Display',
  'Overlays',
  'Menus',
  'Layout',
  'Media & Time',
] as const

export type ComponentGroup = (typeof componentGroups)[number]

export const componentPageEntries = [
  {
    slug: 'accordion',
    title: 'Accordion',
    description: '可折叠内容面板，适合 FAQ、设置项和分组信息。',
    group: 'Layout',
    icon: 'listCollapse',
  },
  {
    slug: 'ai-chat-dialog',
    title: 'AI Chat Dialog',
    description: '带消息流、输入区和打字反馈的 AI 对话组件。',
    group: 'Overlays',
    icon: 'messageCircleMore',
  },
  {
    slug: 'alert-dialog',
    title: 'Alert Dialog',
    description: '用于危险操作确认的阻断式确认弹窗。',
    group: 'Overlays',
    icon: 'shieldAlert',
  },
  {
    slug: 'alert',
    title: 'Alert',
    description: '用于成功、警告、错误和说明信息的提示容器。',
    group: 'Feedback & Status',
    icon: 'triangleAlert',
  },
  {
    slug: 'aspect-ratio',
    title: 'Aspect Ratio',
    description: '保持媒体内容固定宽高比的布局容器。',
    group: 'Layout',
    icon: 'ratio',
  },
  {
    slug: 'avatar',
    title: 'Avatar',
    description: '展示用户头像、缩写和状态的轻量资料组件。',
    group: 'Data Display',
    icon: 'circleUserRound',
  },
  {
    slug: 'badge',
    title: 'Badge',
    description: '用于状态、标签和分类标识的紧凑型标签。',
    group: 'Feedback & Status',
    icon: 'badge',
  },
  {
    slug: 'breadcrumb',
    title: 'Breadcrumb',
    description: '展示当前位置层级路径的导航组件。',
    group: 'Navigation',
    icon: 'route',
  },
  {
    slug: 'button',
    title: 'Button',
    description: '支持变体、尺寸、图标和交互状态的基础按钮。',
    group: 'Buttons & Actions',
    icon: 'mousePointerClick',
  },
  {
    slug: 'calendar',
    title: 'Calendar',
    description: '支持单选、范围和禁用日期的日历选择器。',
    group: 'Media & Time',
    icon: 'calendarDays',
  },
  {
    slug: 'card',
    title: 'Card',
    description: '用于组织标题、描述、正文和操作区的卡片容器。',
    group: 'Data Display',
    icon: 'squareStack',
  },
  {
    slug: 'carousel',
    title: 'Carousel',
    description: '基于 Embla 的轮播容器，支持多种布局方式。',
    group: 'Media & Time',
    icon: 'galleryHorizontal',
  },
  {
    slug: 'checkbox',
    title: 'Checkbox',
    description: '支持多选、禁用和列表组合的复选框组件。',
    group: 'Form Inputs',
    icon: 'squareCheck',
  },
  {
    slug: 'collapsible',
    title: 'Collapsible',
    description: '按需展开内容的轻量折叠容器。',
    group: 'Layout',
    icon: 'chevronsUpDown',
  },
  {
    slug: 'command',
    title: 'Command',
    description: '基于 cmdk 的命令面板与快速导航组件。',
    group: 'Menus',
    icon: 'command',
  },
  {
    slug: 'context-menu',
    title: 'Context Menu',
    description: '右键触发的上下文菜单，适合文件和列表操作。',
    group: 'Menus',
    icon: 'squareMenu',
  },
  {
    slug: 'dialog',
    title: 'Dialog',
    description: '用于表单、详情和确认流程的模态对话框。',
    group: 'Overlays',
    icon: 'messageSquare',
  },
  {
    slug: 'drawer',
    title: 'Drawer',
    description: '底部滑出的移动端风格抽屉容器。',
    group: 'Overlays',
    icon: 'panelBottomOpen',
  },
  {
    slug: 'dropdown-menu',
    title: 'Dropdown Menu',
    description: '按钮触发的层级菜单，适合账户和工具操作。',
    group: 'Menus',
    icon: 'chevronDownSquare',
  },
  {
    slug: 'hover-card',
    title: 'Hover Card',
    description: '悬停后展示补充信息的详情卡片。',
    group: 'Data Display',
    icon: 'mousePointer2',
  },
  {
    slug: 'input',
    title: 'Input',
    description: '支持文本、邮箱、密码和状态反馈的输入框。',
    group: 'Form Inputs',
    icon: 'textCursorInput',
  },
  {
    slug: 'input-otp',
    title: 'Input OTP',
    description: '多槽位验证码输入组件，适合短信和邮箱验证。',
    group: 'Form Inputs',
    icon: 'keyRound',
  },
  {
    slug: 'label',
    title: 'Label',
    description: '表单字段和说明文字的语义标签组件。',
    group: 'Form Inputs',
    icon: 'tags',
  },
  {
    slug: 'menubar',
    title: 'Menubar',
    description: '桌面应用风格的顶部菜单栏组件。',
    group: 'Menus',
    icon: 'menuSquare',
  },
  {
    slug: 'navigation-menu',
    title: 'Navigation Menu',
    description: '支持触发器、内容面板和视口的站点导航组件。',
    group: 'Navigation',
    icon: 'panelTop',
  },
  {
    slug: 'pagination',
    title: 'Pagination',
    description: '适用于列表和表格的页码导航组件。',
    group: 'Navigation',
    icon: 'ellipsis',
  },
  {
    slug: 'popover',
    title: 'Popover',
    description: '点击触发的浮层内容容器。',
    group: 'Data Display',
    icon: 'appWindow',
  },
  {
    slug: 'progress',
    title: 'Progress',
    description: '用于上传、任务和容量占比的进度展示组件。',
    group: 'Feedback & Status',
    icon: 'chartNoAxesColumnIncreasing',
  },
  {
    slug: 'radio-group',
    title: 'Radio Group',
    description: '用于互斥选项选择的单选组组件。',
    group: 'Form Inputs',
    icon: 'circleDot',
  },
  {
    slug: 'resizable',
    title: 'Resizable',
    description: '支持拖拽调整布局比例的面板组。',
    group: 'Layout',
    icon: 'panelLeftDashed',
  },
  {
    slug: 'scroll-area',
    title: 'Scroll Area',
    description: '带统一滚动样式的可滚动区域容器。',
    group: 'Layout',
    icon: 'scrollText',
  },
  {
    slug: 'select',
    title: 'Select',
    description: '支持分组和自定义触发器的下拉选择器。',
    group: 'Form Inputs',
    icon: 'listFilter',
  },
  {
    slug: 'separator',
    title: 'Separator',
    description: '用于水平或垂直分隔内容的基础分隔线。',
    group: 'Layout',
    icon: 'separatorHorizontal',
  },
  {
    slug: 'sheet',
    title: 'Sheet',
    description: '从四个方向滑出的面板容器。',
    group: 'Overlays',
    icon: 'panelRightOpen',
  },
  {
    slug: 'skeleton',
    title: 'Skeleton',
    description: '用于加载态占位的骨架屏组件。',
    group: 'Feedback & Status',
    icon: 'scanSearch',
  },
  {
    slug: 'slider',
    title: 'Slider',
    description: '适合范围、强度和价格选择的滑块组件。',
    group: 'Form Inputs',
    icon: 'slidersHorizontal',
  },
  {
    slug: 'sonner',
    title: 'Sonner',
    description: '基于全局 Toaster 的轻提示调用方式演示。',
    group: 'Feedback & Status',
    icon: 'bellRing',
  },
  {
    slug: 'spinner',
    title: 'Spinner',
    description: '用于提交、加载和等待状态的旋转指示器。',
    group: 'Feedback & Status',
    icon: 'loaderCircle',
  },
  {
    slug: 'stepper',
    title: 'Stepper',
    description: '按步骤展示流程进度和当前位置的组件。',
    group: 'Navigation',
    icon: 'listOrdered',
  },
  {
    slug: 'switch',
    title: 'Switch',
    description: '适合二元开关和设置项切换的组件。',
    group: 'Form Inputs',
    icon: 'toggleLeft',
  },
  {
    slug: 'table',
    title: 'Table',
    description: '适合结构化列表、状态和金额展示的表格组件。',
    group: 'Data Display',
    icon: 'table2',
  },
  {
    slug: 'tabs',
    title: 'Tabs',
    description: '在同一页面切换内容区域的标签页组件。',
    group: 'Navigation',
    icon: 'folders',
  },
  {
    slug: 'textarea',
    title: 'Textarea',
    description: '适合多行输入、评论和备注的文本域组件。',
    group: 'Form Inputs',
    icon: 'text',
  },
  {
    slug: 'timeline',
    title: 'Timeline',
    description: '按时间顺序展示事件和里程碑的垂直时间线。',
    group: 'Data Display',
    icon: 'clock3',
  },
  {
    slug: 'toggle',
    title: 'Toggle',
    description: '单个开关按钮，适合工具栏和格式控制。',
    group: 'Buttons & Actions',
    icon: 'toggleRight',
  },
  {
    slug: 'toggle-group',
    title: 'Toggle Group',
    description: '支持单选和多选的切换按钮组。',
    group: 'Buttons & Actions',
    icon: 'group',
  },
  {
    slug: 'tooltip',
    title: 'Tooltip',
    description: '悬停时显示额外说明的轻量浮层组件。',
    group: 'Data Display',
    icon: 'badgeInfo',
  },
  {
    slug: 'tree',
    title: 'Tree',
    description: '支持层级展开和搜索过滤的树形结构组件。',
    group: 'Data Display',
    icon: 'folderTree',
  },
] as const

export type ComponentSlug = (typeof componentPageEntries)[number]['slug']

export type ComponentPageEntry = (typeof componentPageEntries)[number]

export type ComponentIconKey = (typeof componentPageEntries)[number]['icon']

export const componentPageMap = Object.fromEntries(
  componentPageEntries.map((entry) => [entry.slug, entry])
) as Record<ComponentSlug, ComponentPageEntry>

export const componentPageGroups = componentGroups.map((group) => ({
  group,
  entries: componentPageEntries.filter((entry) => entry.group === group),
}))

export function getComponentPagePath(slug: ComponentSlug) {
  return `/${slug}`
}
